const langArr = {
///main-page
"unit" :  {
        "eng": "Two<aa>p</aa>Stripes<aa>p</aa>in red<aa>p</aa>collor",
        "ukr": "Дві полоси",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "fbi": {
        "eng": "Make<aaa>p</aaa>an<aaa>p</aaa>Order",
        "ukr": "Придбати",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    },
    "sbi": {
        "eng": "Make<aaa>p</aaa>an<aaa>p</aaa>Order",
        "ukr": "Придбати",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "tbi": {
        "eng": "Make<aaa>p</aaa>an<aaa>p</aaa>Order",
        "ukr": "Придбати",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    ///////////////////////////////grid

    "showOddButton": {
        "eng": "Male",
        "ukr": "Чоловічі",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    },

    "showEvenButton": {
        "eng": "Female",
        "ukr": "Жіночі",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    },

    "showAllButton": {
        "eng": "All",
        "ukr": "Всі",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    },

    "product-button1": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button2": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button3": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button4": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
  
    "product-button5": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button6": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button7": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button8": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button9": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button10": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button11": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button12": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
  
    "product-button13": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button14": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button15": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 
    "product-button16": {
        "eng": "Buy<aaaa>p</aaaa>Now",
        "ukr": "Придбати Зараз",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "",
    }, 

    
    ///Basement
    "about": {
        "eng": "About Us",
        "ukr": "Про Нас",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "", 
    }, 
    ///navbar
    "privacy": {
        "eng": "Privacy",
        "ukr": "Приватність",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "", 
    }, 
    ///navbar
    "conditions": {
        "eng": "Terms and Conditions",
        "ukr": "Умови",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "", 
    }, 
    ///navbar
    "delivery": {
        "eng": "Delivery",
        "ukr": "Доставка",
        "esp": "",
        "ita": "",
        "fra": "",
        "deu": "",
        "pol": "",
        "kaz": "",
        "uzb": "", 
    }, 
}

